import type { ShareConfig } from "@/store/shareStore"

export const DEFAULT_SHARE_CONFIG: ShareConfig = {
    platforms: [
        { id: "facebook", enabled: true, order: 0 },
        { id: "twitter", enabled: true, order: 1 },
        { id: "linkedin", enabled: true, order: 2 },
        { id: "pinterest", enabled: false, order: 3 },
        { id: "reddit", enabled: false, order: 4 },
        { id: "whatsapp", enabled: true, order: 5 },
        { id: "telegram", enabled: false, order: 6 },
        { id: "bluesky", enabled: false, order: 7 },
        { id: "mastodon", enabled: false, order: 8 },
        { id: "threads", enabled: false, order: 9 },
        { id: "tumblr", enabled: false, order: 10 },
        { id: "pocket", enabled: false, order: 11 },
        { id: "flipboard", enabled: false, order: 12 },
        { id: "hackernews", enabled: false, order: 13 },
        { id: "buffer", enabled: false, order: 14 },
        { id: "wechat", enabled: false, order: 15 },
        { id: "line", enabled: false, order: 16 },
        { id: "viber", enabled: false, order: 17 },
        { id: "sms", enabled: false, order: 18 },
        { id: "print", enabled: false, order: 19 },
        { id: "email", enabled: true, order: 20 },
        { id: "copy", enabled: true, order: 21 },
    ],
    style: {
        buttonStyle: "icon-only",
        buttonShape: "rounded",
        size: "medium",
        customSize: 40,
        useUnifiedColor: false,
        unifiedColor: "#333333",
        unifiedHoverColor: "#555555",
    },
    layout: {
        mode: "horizontal",
        spacing: 8,
        floatingPosition: "left",
        floatingOffsetX: 16,
        floatingOffsetY: 50,
        flyInPosition: "bottom-left",
        flyInTrigger: "scroll",
        flyInScrollPercent: 50,
        flyInTimeDelay: 5,
        flyInDismissable: true,
    },
    shareText: {
        customText: "",
        customUrl: "",
        usePageMeta: true,
    },
    animation: {
        hoverEffect: "scale",
        duration: 200,
    },
    showCounts: false,
    analytics: {
        enabled: false,
        events: [],
    },
    follow: {
        profiles: [],
        buttonStyle: "icon-text",
        buttonShape: "rounded",
        size: "medium",
        showCounts: false,
        useUnifiedColor: false,
        unifiedColor: "#333333",
    },
    imageSharing: {
        enabled: false,
        platforms: ["pinterest", "facebook", "twitter"],
        minImageWidth: 200,
        minImageHeight: 200,
        position: "top-right",
    },
    clickToTweets: [],
    contentLocker: {
        enabled: false,
        message: "Share this article to unlock the rest of the content!",
        platforms: ["facebook", "twitter", "linkedin"],
        blurContent: true,
        lockedContentId: "",
    },
    shareCountConfig: {
        enabled: false,
        facebookAppId: "",
        cacheTTLMinutes: 60,
    },
    og: {
        ogTitle: "",
        ogDescription: "",
        ogImage: "",
        ogUrl: "",
        ogType: "website",
        ogSiteName: "",
        twitterCard: "summary_large_image",
        twitterTitle: "",
        twitterDescription: "",
        twitterImage: "",
        twitterSite: "",
        twitterCreator: "",
    },
}
